var wordBank = [
  "aceite de aguacate",
  "aguacate",
  "ajo",
  "ajo molido",
  "alfredo",
  "almendras",
  "avena",
  "azucar",
  "bagel 2 cajas leche",
  "bell pepper",
  "berenjena",
  "bolsa simple 1/4",
  "caja de harinade pastel",
  "calabazitas",
  "camotes",
  "carne d aburguesa",
  "carne de res",
  "cebolla",
  "chayote",
  "chicharron",
  "chicken broth swanson",
  "chile d arbol",
  "chile de arbol",
  "chile pasilla",
  "chile serrano",
  "chips",
  "cilantro",
  "coco",
  "coka",
  "corn meal",
  "costillas",
  "costillitas",
  "cotija",
  "cranberry juice",
  "crema de cafe",
  "crema p cafe",
  "doritos",
  "elotes bolsa",
  "espinacas",
  "french fries",
  "french roll",
  "garbanzo",
  "garbanzos pimienta con limon",
  "head & shoulders",
  "hongo",
  "huevos",
  "jamon",
  "jamón",
  "jicama",
  "jitomate",
  "jogurt",
  "kimchi",
  "leche",
  "lechuga",
  "lechugas",
  "lentejas",
  "limon",
  "longaniza",
  "mantequilla",
  "manzana fuji",
  "manzana gala",
  "manzana verde",
  "maple syrup",
  "mayonesa",
  "mayonesa save",
  "maíz de posole",
  "naranjas",
  "nueces mixtos sin sal",
  "pan de caja",
  "pan p hamburguesa",
  "papaya",
  "papel encerado",
  "pata d pollo",
  "pepino",
  "pepper jack",
  "pera",
  "pierna d pollo",
  "pierna d res",
  "platano",
  "platos",
  "pledge",
  "pollo entero",
  "queso cotija",
  "queso crema",
  "repollo",
  "ritz",
  "rollo",
  "romero",
  "royo de cocina",
  "sal",
  "salchicha",
  "salmon",
  "sopas",
  "special k cereal",
  "spray p bano",
  "sprite",
  "tapatio",
  "tilapia",
  "toallas",
  "tocino",
  "tortillas d harina",
  "tortillas de pita",
  "tostadas",
  "vainilla",
  "verdura congelada",
  "zanahoria",
];

var costco = ["Pledge", "Spray p bano", "cranberry juice"];

var supe = ["Lechuga", "Limon"];

var other = [
  "Aceite de aguacate",
  "Head & Shoulders",
  "Papel Encerado",
  "Bolsa Simple 1/4",
  "Corn Meal",
];

export default wordBank;
