var wordBank = [
  "Pimienta con limon",
  "Ajo molido",
  "Queso cotija ",
  "Queso pepper jack",
  "Jamón ",
  "Queso crema ",
  "Crema p cafe",
  "Elotes bolsa",
  "Carne d aburguesa ",
  "Maple Syrup",
  "Mayonesa save ",
  "Chicken broth Swanson ",
  "Carne de res",
  "Lechuga",
  "Limon",
  "Spray p bano",
  "Pledge",
  "Corn Meal",
  "Head and Shoulders",
  "Bolsa Simple 1/4",
  "Aceite de Aguacate",
  "Caja de Harinade Pastel",
  "Platos",
  "Papel encerado",
  "Toallas",
];

export default wordBank;
